# Generated by Django 4.2.7 on 2026-02-12 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de la mission")),
                (
                    "duration_hours",
                    models.IntegerField(verbose_name="Durée réelle (heures)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("realise", "Réalisé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "db_table": "appointments",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="Nom du contact"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("finance", "Finance"),
                            ("tech", "Technologie"),
                            ("sante", "Santé"),
                            ("industrie", "Industrie"),
                            ("education", "Éducation"),
                            ("commerce", "Commerce"),
                        ],
                        max_length=50,
                        verbose_name="Secteur",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("consultant", "Consultant"),
                            ("senior", "Consultant Senior"),
                            ("manager", "Manager"),
                        ],
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Date d'embauche")),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Taux horaire (€)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "db_table": "employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° facture"
                    ),
                ),
                (
                    "amount_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant HT (€)"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "amount_ttc",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant TTC (€)"
                    ),
                ),
                ("issued_date", models.DateField(verbose_name="Date d'émission")),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emise", "Émise"),
                            ("payee", "Payée"),
                            ("en_retard", "En retard"),
                        ],
                        default="emise",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.appointment",
                        verbose_name="Mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "db_table": "invoices",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du service"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strategie", "Stratégie"),
                            ("it", "IT & Digital"),
                            ("rh", "Ressources Humaines"),
                            ("finance", "Finance & Audit"),
                            ("marketing", "Marketing"),
                            ("organisation", "Organisation"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix de base HT (€)",
                    ),
                ),
                (
                    "duration_hours",
                    models.IntegerField(verbose_name="Durée estimée (heures)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (€)"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Date de paiement")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("carte", "Carte bancaire"),
                            ("cheque", "Chèque"),
                        ],
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.invoice",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.client",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.employee",
                verbose_name="Consultant",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.service",
                verbose_name="Service",
            ),
        ),
    ]
