# Generated by Django 4.2.7 on 2026-02-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(unique=True, verbose_name="ID source OLTP"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                ("sector", models.CharField(max_length=50, verbose_name="Secteur")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
            ],
            options={
                "verbose_name": "Dimension Client",
                "db_table": "dim_client",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="DimDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_date",
                    models.DateField(unique=True, verbose_name="Date complète"),
                ),
                ("year", models.IntegerField(verbose_name="Année")),
                ("quarter", models.IntegerField(verbose_name="Trimestre")),
                ("month", models.IntegerField(verbose_name="Mois")),
                (
                    "month_name",
                    models.CharField(max_length=20, verbose_name="Nom du mois"),
                ),
                ("day", models.IntegerField(verbose_name="Jour")),
                ("day_of_week", models.IntegerField(verbose_name="Jour de la semaine")),
                (
                    "is_weekend",
                    models.BooleanField(default=False, verbose_name="Weekend"),
                ),
            ],
            options={
                "verbose_name": "Dimension Date",
                "db_table": "dim_date",
                "ordering": ["full_date"],
            },
        ),
        migrations.CreateModel(
            name="DimEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(unique=True, verbose_name="ID source OLTP"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nom complet"),
                ),
                ("role", models.CharField(max_length=20, verbose_name="Rôle")),
                ("hire_date", models.DateField(verbose_name="Date d'embauche")),
                (
                    "seniority_years",
                    models.IntegerField(default=0, verbose_name="Ancienneté (années)"),
                ),
            ],
            options={
                "verbose_name": "Dimension Employé",
                "db_table": "dim_employee",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="DimService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(unique=True, verbose_name="ID source OLTP"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du service"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Catégorie")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix de base HT"
                    ),
                ),
                (
                    "duration_hours",
                    models.IntegerField(verbose_name="Durée estimée (h)"),
                ),
            ],
            options={
                "verbose_name": "Dimension Service",
                "db_table": "dim_service",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FactSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_appointment_id",
                    models.IntegerField(unique=True, verbose_name="ID mission source"),
                ),
                ("duration_hours", models.IntegerField(verbose_name="Durée (heures)")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Taux horaire (€)"
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant HT (€)"
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant TTC (€)"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payée")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dw.dimclient",
                        verbose_name="Client",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dw.dimdate",
                        verbose_name="Date",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dw.dimemployee",
                        verbose_name="Consultant",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dw.dimservice",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fait Vente",
                "verbose_name_plural": "Faits Ventes",
                "db_table": "fact_sales",
                "ordering": ["-date"],
            },
        ),
    ]
