# Generated by Django 4.2.7 on 2026-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dw", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimclient",
            name="company_name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Raison sociale"
            ),
        ),
        migrations.AlterField(
            model_name="dimclient",
            name="sector",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Secteur"
            ),
        ),
        migrations.AlterField(
            model_name="dimdate",
            name="full_date",
            field=models.DateField(
                db_index=True, unique=True, verbose_name="Date complète"
            ),
        ),
        migrations.AlterField(
            model_name="dimemployee",
            name="full_name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Nom complet"
            ),
        ),
        migrations.AlterField(
            model_name="dimemployee",
            name="role",
            field=models.CharField(db_index=True, max_length=20, verbose_name="Rôle"),
        ),
        migrations.AlterField(
            model_name="dimservice",
            name="category",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Catégorie"
            ),
        ),
        migrations.AlterField(
            model_name="factsales",
            name="total_ht",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant HT (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="factsales",
            name="total_ttc",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant TTC (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="factsales",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Taux horaire (CHF)"
            ),
        ),
        migrations.AddIndex(
            model_name="factsales",
            index=models.Index(fields=["date", "client"], name="idx_fact_date_client"),
        ),
        migrations.AddIndex(
            model_name="factsales",
            index=models.Index(
                fields=["date", "employee"], name="idx_fact_date_employee"
            ),
        ),
        migrations.AddIndex(
            model_name="factsales",
            index=models.Index(
                fields=["date", "service"], name="idx_fact_date_service"
            ),
        ),
        migrations.AddIndex(
            model_name="factsales",
            index=models.Index(fields=["is_paid"], name="idx_fact_is_paid"),
        ),
    ]
