# Generated by Django 4.2.7 on 2026-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_revenue_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000,
                        help_text="Chiffre d'affaires HT mensuel visé.",
                        max_digits=12,
                        verbose_name="Objectif CA mensuel (CHF)",
                    ),
                ),
                (
                    "occupation_rate_target",
                    models.FloatField(
                        default=75.0,
                        help_text="Taux d'occupation cible des consultants.",
                        verbose_name="Objectif taux d'occupation (%)",
                    ),
                ),
                (
                    "inactivity_months_threshold",
                    models.IntegerField(
                        default=3,
                        help_text="Nombre de mois sans mission pour considérer un client inactif.",
                        verbose_name="Seuil d'inactivité client (mois)",
                    ),
                ),
                (
                    "receivables_alert_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Montant HT à partir duquel les créances déclenchent une alerte.",
                        max_digits=12,
                        verbose_name="Seuil d'alerte créances (CHF)",
                    ),
                ),
                (
                    "average_basket_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        help_text="Panier moyen HT par mission visé.",
                        max_digits=10,
                        verbose_name="Objectif panier moyen (CHF)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Paramètre stratégique",
                "verbose_name_plural": "Paramètres stratégiques",
            },
        ),
    ]
